name: Feature Request
description: Suggest a feature for Motion2MIDI
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature idea! Please describe it below.

  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: A clear description of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Need
      description: What problem would this feature solve? Why do you need it?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: How would you use this feature in your workflow?
      placeholder: |
        When I'm producing music, I would...
        This would help me to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you imagine this feature working?
      placeholder: Maybe add a button that...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I currently work around this by...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Any other context, mockups, screenshots, or examples.
        
        Tip: You can attach images by dragging & dropping them here.
